name = "Bafserve"
author = "Regular Baf"
version = "0.6.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ca57bd81a018af889c90b25a8c76efd7265617fc29df4f3192f9ac0e27779a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
