name = "Wandering Collector"
filename = "wanderingcollector-1.1.1+mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/enYiOcBu/versions/1.1.1+mc1.18.2/wanderingcollector-1.1.1%2Bmc1.18.2.jar"
hash-format = "sha1"
hash = "6a427b2f4414c1aa5b78cf03a8ba4fa435c11560"

[update]
[update.modrinth]
mod-id = "enYiOcBu"
version = "ckY3Hixa"
